version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - apt-get update && apt-get install -y zip

  pre_build:
    commands:
      - echo Preparing build environment
      - aws --version

  build:
    commands:
      - echo Starting the build phase
      - echo "Building the application"
      - echo "Tagging the Docker image"

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
