version: 0.2

phases:
  install:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 600897147573.dkr.ecr.eu-west-3.amazonaws.com
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - $(aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 600897147573.dkr.ecr.eu-west-3.amazonaws.com)
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-image .  # Construction de l'image Docker avec le Dockerfile
  post_build:
    commands:
      - echo "Tagging the Docker image..."
      - docker tag my-image:latest 600897147573.dkr.ecr.eu-west-3.amazonaws.com/coucou:latest
      - echo "Pushing the Docker image to ECR..."
      - docker push 600897147573.dkr.ecr.eu-west-3.amazonaws.com/coucou:latest
