version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - apt-get update && apt-get install -y zip

  pre_build:
    commands:
      - echo Preparing build environment
      - aws --version

  build:
    commands:
      - echo Starting the build phase
      - echo "Building the application"
      - echo "Tagging the Docker image"
      - mkdir -p build  # Crée le dossier "build" si ce n'est pas déjà fait
      - echo "Sample build output" > build/output.txt  # Ajoute un fichier dans le dossier "build" pour tester
      - echo "Generating imagedefinitions.json file"
      - printf '[{"name":"my-container","imageUri":"nginx:latest"}]' > build/imagedefinitions.json

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
  discard-paths: no
  base-directory: build
