version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the project"
      - echo "Build completed successfully"
