version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-west-3"
    REPOSITORY_URI: "600897147573.dkr.ecr.eu-west-3.amazonaws.com/edureka1"

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y jq

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Creating imagedefinitions.json file...
      - echo "[{\"name\":\"edureka1\",\"imageUri\":\"$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
