version: 0.2

phases:
  install:
    commands:
      - echo "Install phase: setting up dependencies"
  build:
    commands:
      - echo "Build phase: compiling code"
      - ls -la
  post_build:
    commands:
      - echo "Post-build phase: finalizing build process"

artifacts:
  files:
    - "**/*"
  discard-paths: yes
