version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update && apt-get install -y zip curl unzip
      - echo "Installing Terraform"
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update && apt-get install -y terraform
      - echo "Copying Terraform project from the host machine"
      - cp -R /path/to/local/terraform_project .

  pre_build:
    commands:
      - echo "Checking AWS CLI version"
      - aws --version
      - echo "Verifying Terraform version"
      - terraform -version

  build:
    commands:
      - echo "Navigating to the Terraform project directory"
      - cd terraform_project
      - echo "Initializing Terraform"
      - terraform init
      - echo "Validating Terraform configuration"
      - terraform validate
      - echo "Applying Terraform configuration"
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform apply completed"
      - echo "Checking S3 bucket replication configuration"
      - aws s3api get-bucket-replication --bucket <Secondary-S3-Bucket> || true

artifacts:
  files:
    - '**/*'
  discard-paths: no
