version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Starting install phase"
      - echo "Installing dependencies"
      - pip install --upgrade pip
  build:
    commands:
      - echo "Starting build phase"
      - echo "This is where the build process happens"
      - ls -la
      - echo "Build phase completed successfully"
  post_build:
    commands:
      - echo "Starting post-build phase"
      - echo "Post-build actions completed"
artifacts:
  files:
    - "**/*"
