version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y jq
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - $(aws ecr get-login-password --region us-west-1) | docker login --username AWS --password-stdin <your-ecr-uri>
  build:
    commands:
      - echo Build started on `date`
      - docker build -t <your-ecr-uri>:latest .
      - docker tag <your-ecr-uri>:latest <your-ecr-uri>:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push <your-ecr-uri>:latest
      - docker push <your-ecr-uri>:$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files:
    - imagedefinitions.json
